config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  resources :blogs, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  resources :sessions
  resources :favorites, only: [:create, :destroy, :index]
  resources :application
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :image, presence: true
  before_validation { email.downcase! }
  has_many :blogs
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :require_logged_in

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
    @user = @blog.user
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def new
    @blog = Blog.new
  end
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path, notice: "ブログを作成しました！"
      BlogMailer.blog_mail(@blog).deliver
    else
      render :new
    end
  end
  def confirm
    @blog = Blog.new(blog_params)
  end

  def edit
    @blog = Blog.find(params[:id])
    if @blog.user != current_user
      redirect_to blogs_path, notice: "権限がありません。"
    end
  end
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました。"
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "削除しました。"
  end

  private
  def blog_params
    params.require(:blog).permit(:image, :content, :image_cache)
  end

  def require_logged_in
    unless logged_in?
      redirect_to new_session_path, notice: "ログインしてください。"
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
  def index
    @favorites = current_user.favorites
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:notice] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:index, :show]

  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @blogs = @user.blogs
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to blogs_path, notice: "権限がありません。"
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: "編集しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

  def require_logged_in
    unless logged_in?
      redirect_to new_session_path, notice: "ログインしてください。"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end

end

app/views/blogs/confirm.html.erb
<% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@blog.errors.count, "error") %> エラーによって <%= @blog.content %> を保存できませんでした。</h2>
    <ul>
    <% @blog.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @blog, local: true, url: blogs_path, method: :post) do |f|  %>
  <p><%= f.text_area :content %></p>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= f.hidden_field :image %>
  <%= f.hidden_field :image_cache %>
  <p><%= f.submit "投稿" %></p>
<% end %>
<%= link_to "一覧に戻る" ,blogs_path %>

app/views/blogs/edit.html.erb
<% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this <%= @blog.content %> from being saved:</h2>
    <ul>
    <% @blog.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @blog, local: true, url: blog_path(@blog.id), method:"patch") do |f| %>
  <p><%= f.text_area :content %></p>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= f.file_field :image %>
  <p><%= f.submit "保存" %></p>
<% end %>
<%= link_to "一覧に戻る" ,blogs_path %>

app/views/blogs/index.html.erb
<% @blogs.each do |blog| %>
  <div class="feed center-block">
    <div class="name_area">
      <p class="thumb_photo"><%= link_to image_tag(blog.user.image.url, class: "img-responsive"), user_path(blog.user.id)  %></p>
      <p class="thumb_name"><%= link_to blog.user.name, user_path(blog.user.id) %></p>
    </div>
    <p><%= link_to image_tag(blog.image.url, class: "img-responsive"), blog_path(blog.id)  %></p>
    <div class="sentence_area">
      <p class="sentence"><%= link_to blog.content, blog_path(blog.id) %></p>
      <p class="time"><%= blog.created_at %></p>
    </div>
  </div>
<% end %>

app/views/blogs/new.html.erb
<% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this <%= @blog.content %> from being saved:</h2>
    <ul>
    <% @blog.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @blog, local: true, url: confirm_blogs_path) do |f|  %>
  <p><%= f.text_area :content %></p>
  <%= image_tag(@bog.image.url) if @blog.image && @blog.image.url %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <p><%= f.submit "確認画面へ" %></p>
<% end %>
<%= link_to "一覧に戻る" ,blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="feed center-block">
  <div class="name_area">
    <p class="thumb_photo"><%= image_tag @blog.user.image.url %></p>
    <p class="thumb_name"><%= @blog.user.name %></p>
  </div>
  <p><%= image_tag @blog.image.url, class: "img-responsive" %></p>
<div class="sentence_area">
  <p class="sentence"><%= @blog.content %></p>
  <p class="time"><%= @blog.created_at %></p>
</div>
  <% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to "お気に入り解除する",favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <%= link_to "お気に入りする", favorites_path(blog_id: @blog.id), method: :post %>
  <% end %>
  <% end %>

<div class="edit_area">
<% if current_user == @user %>
  <%= link_to '編集', edit_blog_path(@blog) %> |
  <%= link_to '削除', blog_path(@blog.id) ,method: :delete %>
<% end %>
  <%= link_to '投稿一覧', blogs_path %>
</div>

</div>

app/views/favorites/index.html.erb
<h2>お気に入り</h2>
<% @favorites.each do |favorite| %>
<div class="feed center-block">
  <p><%= link_to image_tag(favorite.blog.image.url, class: "img-responsive"), blog_path(favorite.blog.id) %></p>
  <div class="sentence_area"><p><%= link_to favorite.blog.content, blog_path(favorite.blog.id) %></p></div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Bootstrap</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1><%= link_to "InstaApp", blogs_path,class: "navbar-brand" %></h1>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "＋新規投稿" ,new_blog_path %></li>
              <li><%= link_to "ユーザー一覧" ,users_path %></li>
              <li><%= link_to "お気に入り" ,favorites_path %></li>
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "サインアップ", new_user_path %></li>
              <li><%= link_to "ログイン", new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true, url: user_path(@user.id), method: :patch) do |f| %>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>
  <p><%= f.label :email %>
  <%= f.email_field :email %></p>
  <p><%= f.label :password %>
  <%= f.text_field :password %></p>
  <p><%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %></p>
  <p><%= f.label :イメージ %></p>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <p><%= f.file_field :image %></p>
  <%= f.submit "保存" %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<div id = "user_page">
  <% @users.each do |user| %>
  <div class="user_box clearfix">
    <p class="photo_user"><%= link_to image_tag(user.image.url), user_path(user.id) %></p>
    <p class="name_user"><%= link_to user.name, user_path(user.id) %></p>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <p><%= f.label :イメージ %>
  <%= f.file_field :image %></p>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>
  <p><%= f.label :email %>
  <%= f.email_field :email %></p>
  <p><%= f.label :password %>
  <%= f.text_field :password %></p>
  <p><%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %></p>
  <%= f.submit "サインアップ" %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p><%= @user.email %></p>

<div class="user_box clearfix">
  <p class="photo_user"><%= image_tag @user.image.url %></p>
  <% if current_user == @user %>
    <p><%= link_to "編集", edit_user_path(@user.id) %></p>
  <% end %>
</div>

<% @blogs.each do |blog| %>
  <div class="feed center-block">
    <p><%= link_to image_tag(blog.image.url, class: "img-responsive"), blog_path(blog.id) %></p>
    <div class="sentence_area"><p><%= link_to blog.content, blog_path(blog.id) %></p></div>
  </div>
<% end %>